name: RDMA-SYS-CI
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  schedule: [ cron: "0 */24 * * *" ]

env:
  RUST_TOOLCHAIN: 1.87.0
  DEPENDENCIES: "libibverbs-dev librdmacm-dev"

jobs:
  ci:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        command: [ check, build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ${{ env.DEPENDENCIES }}

      - name: Run command
        run: cargo ${{ matrix.command }} --verbose
        